#google_analytics_id:

# standard jekyll configuration

#permalink: /articles/:title
highlighter: pygments
exclude:
#- bin
#- config.rb
- Gemfile
- Gemfile.lock
- gems
#- Procfile
#- Rakefile
#- README.md
#- script
#- vendor

markdown: redcarpet

#github:
#  username:

#disqus:
#  id: